public enum Permissoes {
    HABILITAR_RESTAURANTE("HABILITAR_RESTAURANTE"),
    ALTERAR_PERMISSAO("ALTERAR_PERMISSAO"),
    FAZER_PEDIDOS("FAZER_PEDIDOS"),
    CRIAR_ITENS_CARDAPIO("CRIAR_ITENS_CARDAPIO"),
    REMOVER_ITENS_CARDAPIO("REMOVER_ITENS_CARDAPIO"),
    EDITAR_ITENS_CARDAPIO("EDITAR_ITENS_CARDAPIO"),
    VISUALIZAR_ITENS_CARDAPIO("VISUALIZAR_ITENS_CARDAPIO"),
    APROVAR_PEDIDOS("APROVAR_PEDIDOS"),
    RECUSAR_PEDIDOS("RECUSAR_PEDIDOS"),
    ADICIONAR_FUNCIONARIO("ADICIONAR_FUNCIONARIO"),
    REMOVER_FUNCIONARIO("REMOVER_FUNCIONARIO");

    public String descricao;

    Permissoes(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao() {
        return descricao;
    }

}

